import Link from "next/link";
import { services } from "./catalog";

export const metadata = { title: "Services | MindReply", description: "Integrated intelligence, data, technology, security, operations, workplace and training services." };

export default function ServicesPage() {
  return <main className="mc-page">
    <nav className="mc-nav" aria-label="Primary navigation"><Link className="mc-brand" href="/">MindReply<small>OPERATING SYSTEM</small></Link><div className="mc-nav-center"><Link href="/platform">Platform</Link><Link href="/operations">Operations</Link><Link href="/services">Services</Link><Link href="/regions">Regions</Link><Link href="/evidence">Evidence</Link></div><div className="mc-nav-right"><span className="mc-state"><i className="mc-dot"/>SYSTEM LIVE</span></div></nav>
    <section className="mc-hero" aria-labelledby="services-title"><div><p className="mc-kicker"><i/>CAPABILITIES / GLOBAL DELIVERY</p><h1 id="services-title">Technology that moves from <em>intelligence to operation.</em></h1><p className="lead">One connected delivery model across intelligence, data, infrastructure, applications, security, operations, workplace and people.</p><div className="mc-actions"><Link className="mc-primary" href="/contact">Discuss a requirement ↗</Link><Link className="mc-secondary" href="/audit">Request an assessment</Link></div></div><aside className="mc-console"><div className="mc-console-top"><span>DELIVERY MODEL</span><b>END TO END</b></div><div className="mc-console-main"><span className="mc-console-label">From challenge to measurable outcome</span><div className="mc-verdict"><strong>Assess → Build → Operate.</strong><span>READY</span></div><p>Every engagement can begin with a focused assessment and expand into implementation, managed operation, and capability transfer.</p></div></aside></section>
    <section className="mc-section" aria-labelledby="capabilities-title"><div className="mc-section-head"><span>CORE CAPABILITIES</span><h2 id="capabilities-title">Eight connected capabilities. One accountable delivery path.</h2></div><div className="mc-rail">{services.map((service) => <Link className="mc-module" key={service.slug} href={`/services/${service.slug}`}><span className="num">{service.number}</span><h3>{service.title}</h3><p>{service.promise}</p><ul>{service.outcomes.map((outcome) => <li key={outcome}>{outcome}</li>)}</ul></Link>)}</div></section>
    <section className="mc-section" aria-labelledby="model-title"><div className="mc-section-head"><span>HOW WE ENGAGE</span><h2 id="model-title">Start where the risk or opportunity is highest.</h2></div><div className="mc-link-grid"><Link className="mc-link-card" href="/audit"><span>01 · Assess</span><b>Find the highest-value gaps ↗</b></Link><Link className="mc-link-card" href="/platform"><span>02 · Build</span><b>Implement the required capability ↗</b></Link><Link className="mc-link-card" href="/operations"><span>03 · Operate</span><b>Monitor, improve and assure ↗</b></Link><Link className="mc-link-card" href="/regions"><span>04 · Expand</span><b>Deploy regionally from one core ↗</b></Link></div></section>
    <section className="mc-closing"><p className="mc-kicker"><i/>REALITY DELTA</p><h2>Move from a technology ambition to a system that can prove its value.</h2><p>We connect strategy, engineering and operations so the outcome is measurable in the systems people actually use.</p><Link className="mc-primary" href="/audit">Start with evidence ↗</Link></section>
    <footer className="mc-footer"><span>MindReply</span><span>INTELLIGENCE · TECHNOLOGY · OPERATIONS</span><div className="mc-footer-links"><Link href="/status">System status ↗</Link><Link href="/contact">Contact ↗</Link></div></footer>
  </main>;
}
